default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-task-manager_development

test:
  <<: *default
  database: rails-task-manager_test
